extends Node2D

# --- Node References ---
@onready var game_data = $"/root/GameData" # Accesses the global Autoload script
@onready var dialogue_box = $DialogueBox/DialogueBox # Assuming the customer's text box
@onready var customer_node = $Customer # Assuming the customer character node

# --- Plate Slot References ---
# Use the exact names of your Area2D slots inside the FoodPlate node (Used for manual checks/debugging)
@onready var slot_go = $FoodPlate/SlotGo
@onready var slot_grow = $FoodPlate/SlotGrow
@onready var slot_glow_veg = $FoodPlate/SlotGlowVeg
@onready var slot_glow_fru = $FoodPlate/SlotGlowFru

# --- Game State ---
var current_required_order: Dictionary = {}
var is_order_served: bool = false # Prevents serving the plate multiple times

# --- Initialization ---
func _ready():
	# 1. Start the game flow by getting the current order
	start_customer_interaction()
	
	# 2. Connect signals from all four plate slots
	# NOTE: The plate_updated signal is no longer used for auto-serving, but can be useful for
	# visual feedback or debugging.
	slot_go.plate_updated.connect(_on_plate_slot_updated)
	slot_grow.plate_updated.connect(_on_plate_slot_updated)
	slot_glow_veg.plate_updated.connect(_on_plate_slot_updated)
	slot_glow_fru.plate_updated.connect(_on_plate_slot_updated)

# --- CUSTOMER & ORDER FUNCTIONS ---

func start_customer_interaction():
	# 1. Get the order from the global GameData manager
	current_required_order = game_data.generate_order_for_day(game_data.current_day)
	
	# 2. Convert the order dictionary to a readable text string
	var order_text = generate_order_text(current_required_order)
	
	# 3. Display the order (Example: use your dialogue box)
	dialogue_box.set_text("I would like " + order_text + " please.")
	
	# 4. Optional: Animate customer entry here
	customer_node.show()


func generate_order_text(order: Dictionary) -> String:
	# Converts the order into a sentence: "rice, chicken, mixed vegetables and a watermelon"
	var items = []
	if order.has("Go"):
		items.append(order["Go"])
	if order.has("Grow"):
		items.append(order["Grow"])
	if order.has("GlowVeg"):
		items.append(order["GlowVeg"])
	if order.has("GlowFru"):
		items.append(order["GlowFru"])
	
	# Format the array into a comma-separated list
	if items.size() > 1:
		var last_item = items.pop_back()
		return items.join(", ") + " and a " + last_item
	elif items.size() == 1:
		return items[0]
	return "nothing" # Should not happen


# --- PUBLIC FUNCTIONS CALLED BY DRAGGABLE PLATE ---

# This is called by food_plate_draggable.gd when the plate is dropped on the Serve Zone.
func serve_completed_plate(plate_contents: Array):
	if is_order_served:
		print("WARNING: Order already served.")
		return
		
	is_order_served = true # Lock the serving process
	
	# 1. Calculate the score based on the contents passed from the plate
	var accuracy_score = calculate_accuracy(plate_contents)
	var reaction_type = get_reaction_type(accuracy_score)
	
	# 2. Trigger the customer's reaction dialogue
	trigger_customer_reaction(reaction_type)
	
	# 3. Process the results
	var money_gained = accuracy_score * 100 # Example: $100 per correct item
	var reputation_change = float(accuracy_score) / 4.0 - 0.5 # Range: -0.5 (0 correct) to +0.5 (4 correct)
	
	var day_result = {
		"accuracy": accuracy_score,
		"reaction": reaction_type,
		"earned_money": money_gained,
		"reputation_change": reputation_change
	}
	
	print("Day Result: ", day_result) # Debug print
	
	# Wait for the customer dialogue to finish before advancing the day
	await get_tree().create_timer(3.0).timeout # Wait 3 seconds for reaction dialogue
	
	# 4. End the day through the global manager
	game_data.end_day(day_result)

# This is called by food_plate_draggable.gd when the plate is dropped on the Trash Zone.
func deduct_score(amount: int):
	# Placeholder for future score/money deduction logic
	print("Deducting %d score/money for trashing a plate." % amount)
	# game_data.add_money(-amount) # Uncomment when money tracking is implemented

# --- Plate Logic (Monitor for Debugging/Feedback) ---
func _on_plate_slot_updated(item_resource_or_null):
	# This function is now just for monitoring and can be used to update a HUD
	# or provide sound feedback when an item is successfully placed/cleared.
	print("Plate slot updated. Item: ", item_resource_or_null)


# --- Scoring and Reaction ---
# Now accepts the array of contents generated by the draggable plate script
func calculate_accuracy(contents_array: Array) -> int:
	var correct_items = 0
	
	# Create a map of the served items for easy lookup: {"Go": "Rice", "Grow": "Chicken"}
	var served_items = {}
	for content in contents_array:
		# Use safe access and check if the resource is valid
		if content.has("item") and content.has("accepted_type") and content["item"] != null:
			# Get the name property from the item resource
			var item_name = content.item.get("item_name", "") 
			served_items[content.accepted_type] = item_name
			
	print("Served Items: ", served_items)
	print("Required Order: ", current_required_order)

	# Compare each required type to the served item
	for food_type in current_required_order.keys():
		var required_item_name = current_required_order[food_type]
		var served_item_name = served_items.get(food_type) # Returns null if type wasn't served
		
		if required_item_name == served_item_name:
			correct_items += 1
			
	return correct_items

func get_reaction_type(score: int) -> String:
	if score == 4:
		return "compliment"
	elif score >= 2:
		return "neutral"
	else:
		return "complaint"

func trigger_customer_reaction(reaction: String):
	# This function changes the customer's dialogue box text and/or facial expression
	var message = ""
	
	match reaction:
		"compliment":
			message = "This is a perfect plate! Exactly what I ordered, thank you!"
			# Optional: customer_node.play_animation("happy")
		"neutral":
			message = "It's close enough, I suppose. Some items were swapped."
			# Optional: customer_node.play_animation("confused")
		"complaint":
			message = "Ugh, this isn't what I asked for at all! Are you even listening?"
			# Optional: customer_node.play_animation("angry")
			
	dialogue_box.set_text(message)
